### ISSUE TITLE
哪些功能没有开源呢？

### ISSUE THREAD

**Issue by jinyan2049** [gitstliu/MysqlToAll#2]
作者，您好，请问，哪些功能没有开源呢？

**Comment by gitstliu** [comment]
mongo 全部未开源。mysql 一小部分未开源,现在mysql仅支持,本地文件、es、kafka、redis、redis-cluster等业务数据的同步,不支持audit模式~

**Comment by gitstliu** [comment]
未开源版本还支持部分高可用功能,如断线回复,尝试重连等等
